export enum Configuration {
  MONGODB_URI = 'MONGODB_URI',
  MONGO_INITDB_ROOT_USERNAME = 'MONGO_INITDB_ROOT_USERNAME',
  MONGO_INITDB_ROOT_PASSWORD = 'MONGO_INITDB_ROOT_PASSWORD',
  MONGO_DATABASE = 'MONGO_DATABASE',
  MONGO_DATABASE_HOST = 'MONGO_DATABASE_HOST',
  MONGO_DATABASE_PORT = 'MONGO_DATABASE_PORT',
  PORT = 'PORT',
}
